spring:
  application:
    name: datastar-spring-mvc
  threads:
    virtual:
      enabled: true
  web:
    resources:
      cache:
        period: 86400

server:
  port: 8080

management:
  server:
    port: 9080

gg:
  jte:
    use-precompiled-templates: true
    localizer:
      inject: true

datastar:
  sse:
    enabled: true
  csp:
    enabled: true
    csp-header: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg [%kvp{}]%n"
  level:
    '[org.apache.catalina.core.ContainerBase]': OFF