global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets:
        - "traefik:8899"

  - job_name: prometheus
    static_configs:
      - targets:
        - "prometheus:9090"

  - job_name: grafana
    static_configs:
      - targets:
        - "grafana:3000"

  - job_name: datastar-spring-mvc
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "datastar-spring-mvc:9080"