@param int playerCount
@param long chaosCounter

<section id="chaosMeter" class="box stack">
    <h3 class="text-layout text-2">Chaos meter</h3>
    <div>
        <div>
            <strong>Number of players:</strong>
            <span>${playerCount}</span>
        </div>
        <div>
            <strong>Chaos counter:</strong>
            <span>${chaosCounter}</span>
        </div>
    </div>
</section>
